---
- name: Configure Web Server & Deploy Django App
  hosts: web
  become: true
  tasks:

    # ✅ 1. Secure EC2 instance
    - name: Disable password-based SSH authentication
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^#?PasswordAuthentication'
        line: 'PasswordAuthentication no'
      notify: Restart SSH

    - name: Apply security updates automatically
      apt:
        upgrade: dist
        update_cache: yes

    - name: Install Fail2Ban
      apt:
        name: fail2ban
        state: present

    - name: Start and enable Fail2Ban
      service:
        name: fail2ban
        state: started
        enabled: yes

    
    # ✅ 2. Install and Configure Web Server
    - name: Install NGINX
      apt:
        name: nginx
        state: present

    - name: Start and enable NGINX
      service:
        name: nginx
        state: started
        enabled: yes

    # ✅ 3. Install PostgreSQL (Optional: MySQL)
    - name: Install PostgreSQL
      apt:
        name: postgresql
        state: present

    - name: Ensure PostgreSQL is running
      service:
        name: postgresql
        state: started
        enabled: yes

    # ✅ 4. Install Required Python Dependencies
    - name: Install Python and dependencies
      apt:
        name: 
          - python3
          - python3-pip
          - python3-venv
        state: present

    - name: Install Django dependencies
      pip:
        name:
          - django
          - gunicorn
          - psycopg2
        executable: pip3

   